"""Static public-contract inventory for the Revision 2 snapshot matrix.

The registry is intentionally literal.  Runtime discovery in the matrix tests is
only an alarm for newly added, removed, or misclassified public contracts; it is
not allowed to manufacture the expected snapshot set.
"""

from __future__ import annotations


PUBLIC_MODEL_CASES = (
    "src.screening.offensive.v3.contracts.authorization.CapitalAuthorizationEnvelope",
    "src.screening.offensive.v3.contracts.base.RationalQuantity",
    "src.screening.offensive.v3.contracts.capital.AuthoritySnapshot",
    "src.screening.offensive.v3.contracts.capital.CapitalLiveOrderRisk",
    "src.screening.offensive.v3.contracts.capital.CapitalPositionRisk",
    "src.screening.offensive.v3.contracts.capital.CapitalRiskSnapshot",
    "src.screening.offensive.v3.contracts.capital.CapitalSnapshot",
    "src.screening.offensive.v3.contracts.capital.CashEconomicEventLeg",
    "src.screening.offensive.v3.contracts.capital.CashReceivableEconomicEventLeg",
    "src.screening.offensive.v3.contracts.capital.CorporateActionRiskComponent",
    "src.screening.offensive.v3.contracts.capital.CostBasisEconomicEventLeg",
    "src.screening.offensive.v3.contracts.capital.DividendReceivable",
    "src.screening.offensive.v3.contracts.capital.EconomicEvent",
    "src.screening.offensive.v3.contracts.capital.EntryReserveRiskComponent",
    "src.screening.offensive.v3.contracts.capital.ExitMandate",
    "src.screening.offensive.v3.contracts.capital.OrderSnapshot",
    "src.screening.offensive.v3.contracts.capital.PendingStressRiskComponent",
    "src.screening.offensive.v3.contracts.capital.PlanSnapshot",
    "src.screening.offensive.v3.contracts.capital.PositionSnapshot",
    "src.screening.offensive.v3.contracts.capital.RiskExposureBucket",
    "src.screening.offensive.v3.contracts.capital.SecurityEconomicEventLeg",
    "src.screening.offensive.v3.contracts.capital.SessionCheckpoint",
    "src.screening.offensive.v3.contracts.capital.ShareReceivable",
    "src.screening.offensive.v3.contracts.capital.ShareReceivableEconomicEventLeg",
    "src.screening.offensive.v3.contracts.capital.StageLossLatchSnapshot",
    "src.screening.offensive.v3.contracts.capital.ValuationMarkEconomicEventLeg",
    "src.screening.offensive.v3.contracts.decision.AuthorizationIssuanceBinding",
    "src.screening.offensive.v3.contracts.decision.CounterfactualDecisionKey",
    "src.screening.offensive.v3.contracts.decision.DecisionLogicalKey",
    "src.screening.offensive.v3.contracts.decision.GatewayExpectedVersions",
    "src.screening.offensive.v3.contracts.decision.GatewayIssuerBinding",
    "src.screening.offensive.v3.contracts.decision.PlanEvidence",
    "src.screening.offensive.v3.contracts.decision.PortfolioDecision",
    "src.screening.offensive.v3.contracts.decision.PortfolioDecisionSeal",
    "src.screening.offensive.v3.contracts.decision.PortfolioOrderLine",
    "src.screening.offensive.v3.contracts.decision.PriorSealEligibilityBinding",
    "src.screening.offensive.v3.contracts.decision.SealReserveLineBinding",
    "src.screening.offensive.v3.contracts.decision.ShadowDecision",
    "src.screening.offensive.v3.contracts.decision.ShadowIssuerBinding",
    "src.screening.offensive.v3.contracts.decision.ShadowOrderLine",
    "src.screening.offensive.v3.contracts.decision.ShadowStageBinding",
    "src.screening.offensive.v3.contracts.decision.StageAdmissionBinding",
    "src.screening.offensive.v3.contracts.decision.StageLossExpectedVersion",
    "src.screening.offensive.v3.contracts.decision.TrustedClockObservation",
    "src.screening.offensive.v3.contracts.decision.TrustedExecutionWindow",
    "src.screening.offensive.v3.contracts.evidence.EvidenceEnvelope",
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord[OutcomeEvidence]",
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord[PlanEvidence]",
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord[SignalEvidence]",
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord[SnapshotEvidence]",
    "src.screening.offensive.v3.contracts.evidence.OutcomeEvidence",
    "src.screening.offensive.v3.contracts.evidence.SignalEvidence",
    "src.screening.offensive.v3.contracts.evidence.SnapshotEvidence",
    "src.screening.offensive.v3.contracts.execution.AuthorizationIssuerRevalidation",
    "src.screening.offensive.v3.contracts.execution.EntryCancellationReceipt",
    "src.screening.offensive.v3.contracts.execution.ExecutionPermit",
    "src.screening.offensive.v3.contracts.execution.ExecutionPermitLine",
    "src.screening.offensive.v3.contracts.execution.ExecutionRevision",
    "src.screening.offensive.v3.contracts.execution.ExecutionRevisionHistory",
    "src.screening.offensive.v3.contracts.execution.PermitCancellationBinding",
    "src.screening.offensive.v3.contracts.execution.PermitEvaluationState",
    "src.screening.offensive.v3.contracts.execution.PermitLineMechanicalBinding",
    "src.screening.offensive.v3.contracts.execution.ReservationLineAllocation",
    "src.screening.offensive.v3.contracts.execution.SendClaimExpectedVersions",
    "src.screening.offensive.v3.contracts.regime.RegimeObservation",
    "src.screening.offensive.v3.contracts.regime.RegimeSourceRevision",
    "src.screening.offensive.v3.contracts.compatibility.LegacyShadowDecisionV2",
    "src.screening.offensive.v3.contracts.compatibility.LegacyShadowOrderLine",
    "src.screening.offensive.v3.contracts.trial.BaselineShadowPolicyBinding",
    "src.screening.offensive.v3.contracts.trial.TargetShadowPolicyBinding",
    "src.screening.offensive.v3.contracts.governance.ApprovalAttestationBinding",
    "src.screening.offensive.v3.contracts.governance.AuthorizationStatus",
    "src.screening.offensive.v3.contracts.governance.BrokerEnablementManifest",
    "src.screening.offensive.v3.contracts.governance.DisasterRecoveryManifest",
    "src.screening.offensive.v3.contracts.governance.EntryFenceAcknowledgement",
    "src.screening.offensive.v3.contracts.governance.EntryFenceRaised",
    "src.screening.offensive.v3.contracts.governance.LineageGrant",
    "src.screening.offensive.v3.contracts.governance.MigrationApprovalManifest",
    "src.screening.offensive.v3.contracts.governance.PolicyActivation",
    "src.screening.offensive.v3.contracts.governance.ProgramLossBudgetBinding",
    "src.screening.offensive.v3.contracts.governance.RiskEpochStarted",
    "src.screening.offensive.v3.contracts.governance.StageManifest",
    "src.screening.offensive.v3.contracts.governance.StatisticalAnalysisPlan",
    "src.screening.offensive.v3.contracts.governance.TrialManifest",
    "src.screening.offensive.v3.contracts.governance.TrustBundle",
    "src.screening.offensive.v3.contracts.trust.Capability",
    "src.screening.offensive.v3.contracts.trust.CurrentTrustHeadWitness",
    "src.screening.offensive.v3.contracts.trust.SignedEnvelope",
    "src.screening.offensive.v3.contracts.trust.VerifiedIssuer",
    "src.screening.offensive.v3.policy.models.ActivePolicyActivationWitness",
    "src.screening.offensive.v3.policy.models.AdvPolicy",
    "src.screening.offensive.v3.policy.models.CapitalPolicy",
    "src.screening.offensive.v3.policy.models.EvidenceGatePolicy",
    "src.screening.offensive.v3.policy.models.ExecutionPolicy",
    "src.screening.offensive.v3.policy.models.PolicySnapshot",
    "src.screening.offensive.v3.policy.models.ProducerIdentity",
    "src.screening.offensive.v3.policy.models.ProducerPolicy",
    "src.screening.offensive.v3.policy.models.RiskPolicy",
    "src.screening.offensive.v3.policy.models.VerifiedPolicyActivation",
    "src.screening.offensive.v3.policy.models.VersionBindings",
    "src.screening.offensive.v3.trust.registry.RootTrustAnchor",
    "src.screening.offensive.v3.trust.registry.SignedTrustBundle",
    "src.screening.offensive.v3.trust.registry.TrustedIssuer",
    "src.screening.offensive.v3.trust.registry.TrustedRegistry",
    "src.screening.offensive.v3.trust.registry.VerifiedTrustBundle",
)

PUBLIC_ENUMS = (
    "src.screening.offensive.v3.contracts.authorization.AuthorizationKind",
    "src.screening.offensive.v3.contracts.base.EvidenceScope",
    "src.screening.offensive.v3.contracts.base.ExecutionMode",
    "src.screening.offensive.v3.contracts.base.SignalStage",
    "src.screening.offensive.v3.contracts.capital.AuthorityState",
    "src.screening.offensive.v3.contracts.capital.EconomicAssetKind",
    "src.screening.offensive.v3.contracts.capital.EconomicEventKind",
    "src.screening.offensive.v3.contracts.capital.EconomicLegDirection",
    "src.screening.offensive.v3.contracts.capital.ExitMandateRevisionKind",
    "src.screening.offensive.v3.contracts.capital.ExitQuantityKnowledge",
    "src.screening.offensive.v3.contracts.capital.ExposureScope",
    "src.screening.offensive.v3.contracts.capital.PositionState",
    "src.screening.offensive.v3.contracts.capital.RiskOrderSide",
    "src.screening.offensive.v3.contracts.capital.SessionPhase",
    "src.screening.offensive.v3.contracts.decision.ClockHealth",
    "src.screening.offensive.v3.contracts.evidence.ProviderPublicationState",
    "src.screening.offensive.v3.contracts.execution.ActiveEntryClaimState",
    "src.screening.offensive.v3.contracts.execution.AuthorizationIssuerVerificationResult",
    "src.screening.offensive.v3.contracts.execution.EconomicProjectionState",
    "src.screening.offensive.v3.contracts.execution.EffectivePositionState",
    "src.screening.offensive.v3.contracts.execution.ExecutionRevisionKind",
    "src.screening.offensive.v3.contracts.execution.ExecutionSide",
    "src.screening.offensive.v3.contracts.execution.OrderState",
    "src.screening.offensive.v3.contracts.execution.OutboxState",
    "src.screening.offensive.v3.contracts.execution.PermitDisposition",
    "src.screening.offensive.v3.contracts.execution.PermitNonceState",
    "src.screening.offensive.v3.contracts.execution.PermitReasonCode",
    "src.screening.offensive.v3.contracts.execution.PlanState",
    "src.screening.offensive.v3.contracts.execution.ReservationState",
    "src.screening.offensive.v3.contracts.governance.AuthorizationLifecycle",
    "src.screening.offensive.v3.contracts.governance.GrantKind",
    "src.screening.offensive.v3.contracts.governance.PrimaryMetric",
    "src.screening.offensive.v3.contracts.risk.ReconciliationLatchState",
    "src.screening.offensive.v3.contracts.risk.RiskLatchState",
    "src.screening.offensive.v3.contracts.risk.RiskSnapshotCompleteness",
    "src.screening.offensive.v3.contracts.risk.RiskSnapshotFreshness",
    "src.screening.offensive.v3.contracts.risk.StageLossLatchState",
    "src.screening.offensive.v3.contracts.trust.ArtifactKind",
    "src.screening.offensive.v3.contracts.trust.IssuerKind",
    "src.screening.offensive.v3.policy.models.CapitalTier",
    "src.screening.offensive.v3.policy.models.MissingAdvBehavior",
    "src.screening.offensive.v3.policy.models.RuntimeMode",
    "src.screening.offensive.v3.contracts.regime.RegimeAdmissionMode",
    "src.screening.offensive.v3.contracts.regime.RegimeObservationReason",
    "src.screening.offensive.v3.contracts.regime.RegimeState",
    "src.screening.offensive.v3.contracts.trial.ShadowPolicySourceKind",
    "src.screening.offensive.v3.contracts.trial.TrialArm",
)

PUBLIC_ALIASES = (
    "src.screening.offensive.v3.contracts.ActiveEvidenceRecord",
    "src.screening.offensive.v3.contracts.ConfidenceLevel",
    "src.screening.offensive.v3.contracts.ExactInteger",
    "src.screening.offensive.v3.contracts.EconomicEventLeg",
    "src.screening.offensive.v3.contracts.Fraction",
    "src.screening.offensive.v3.contracts.MoneyCents",
    "src.screening.offensive.v3.contracts.QuantityUnits",
    "src.screening.offensive.v3.contracts.SchemaVersion",
    "src.screening.offensive.v3.contracts.Sha256",
    "src.screening.offensive.v3.contracts.UtcInstant",
    "src.screening.offensive.v3.contracts.UnitQuanta",
)

PUBLIC_PORTS = (
    "src.screening.offensive.v3.contracts.ports.AuthorizationQueryPort",
    "src.screening.offensive.v3.contracts.ports.CapitalGatewayCommandPort",
    "src.screening.offensive.v3.contracts.ports.CapitalGatewayReadPort",
    "src.screening.offensive.v3.contracts.ports.CapabilityVerifier",
    "src.screening.offensive.v3.contracts.ports.EvidenceQueryPort",
    "src.screening.offensive.v3.contracts.ports.GrowthKernelPort",
)

ARTIFACT_HASH_CASES = (
    "src.screening.offensive.v3.contracts.authorization.CapitalAuthorizationEnvelope",
    "src.screening.offensive.v3.contracts.capital.CapitalRiskSnapshot",
    "src.screening.offensive.v3.contracts.capital.ExitMandate",
    "src.screening.offensive.v3.contracts.compatibility.LegacyShadowDecisionV2",
    "src.screening.offensive.v3.contracts.decision.AuthorizationIssuanceBinding",
    "src.screening.offensive.v3.contracts.decision.GatewayExpectedVersions",
    "src.screening.offensive.v3.contracts.decision.PortfolioDecision",
    "src.screening.offensive.v3.contracts.decision.PortfolioDecisionSeal",
    "src.screening.offensive.v3.contracts.decision.ShadowDecision",
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord[OutcomeEvidence]",
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord[PlanEvidence]",
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord[SignalEvidence]",
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord[SnapshotEvidence]",
    "src.screening.offensive.v3.contracts.execution.AuthorizationIssuerRevalidation",
    "src.screening.offensive.v3.contracts.execution.EntryCancellationReceipt",
    "src.screening.offensive.v3.contracts.execution.ExecutionPermit",
    "src.screening.offensive.v3.contracts.governance.ApprovalAttestationBinding",
    "src.screening.offensive.v3.contracts.governance.AuthorizationStatus",
    "src.screening.offensive.v3.contracts.governance.BrokerEnablementManifest",
    "src.screening.offensive.v3.contracts.governance.DisasterRecoveryManifest",
    "src.screening.offensive.v3.contracts.governance.EntryFenceAcknowledgement",
    "src.screening.offensive.v3.contracts.governance.EntryFenceRaised",
    "src.screening.offensive.v3.contracts.governance.LineageGrant",
    "src.screening.offensive.v3.contracts.governance.MigrationApprovalManifest",
    "src.screening.offensive.v3.contracts.governance.PolicyActivation",
    "src.screening.offensive.v3.contracts.governance.ProgramLossBudgetBinding",
    "src.screening.offensive.v3.contracts.governance.RiskEpochStarted",
    "src.screening.offensive.v3.contracts.governance.StageManifest",
    "src.screening.offensive.v3.contracts.governance.StatisticalAnalysisPlan",
    "src.screening.offensive.v3.contracts.governance.TrialManifest",
    "src.screening.offensive.v3.contracts.governance.TrustBundle",
)

EXCLUDED_MODEL_TYPES = {
    "src.screening.offensive.v3.contracts.base.CanonicalModel": "abstract canonical base",
    "src.screening.offensive.v3.contracts.capital._EconomicEventLeg": "private discriminated-union base",
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord": "bare generic is forbidden; four concrete specializations are registered",
    "src.screening.offensive.v3.contracts.governance.GovernedArtifact": "artifact base",
    "src.screening.offensive.v3.contracts.governance._TwoPersonOneShotManifest": "private manifest base",
}

EVIDENCE_RECORD_SPECIALIZATIONS = (
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord[OutcomeEvidence]",
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord[PlanEvidence]",
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord[SignalEvidence]",
    "src.screening.offensive.v3.contracts.evidence.EvidenceRecord[SnapshotEvidence]",
)

WIRE_MODEL_EXCEPTIONS = ("src.screening.offensive.v3.contracts.trust.SignedEnvelope",)

PROTECTED_PREIMAGE_CASES = (
    "signed_envelope_signing_input",
    "trust_bundle_signature_preimage",
    "issuer_identity_fingerprint",
    "policy_fingerprint",
    "behavior_fingerprint",
    "migration_approval_preimage",
    "broker_enablement_approval_preimage",
    "disaster_recovery_approval_preimage",
)


assert len(PUBLIC_MODEL_CASES) == len(set(PUBLIC_MODEL_CASES)) == 105
assert len(PUBLIC_ENUMS) == len(set(PUBLIC_ENUMS)) == 47
assert len(PUBLIC_ALIASES) == len(set(PUBLIC_ALIASES)) == 11
assert len(PUBLIC_PORTS) == len(set(PUBLIC_PORTS)) == 6
assert len(ARTIFACT_HASH_CASES) == len(set(ARTIFACT_HASH_CASES)) == 31
assert len(EVIDENCE_RECORD_SPECIALIZATIONS) == 4
