from __future__ import annotations

from src.targets.short_trade_target_snapshot_payload_helpers import build_short_trade_target_snapshot_payload


def test_build_short_trade_target_snapshot_payload_surfaces_continuation_and_reversal_keys() -> None:
    payload = build_short_trade_target_snapshot_payload(
        profile="demo-profile",
        signal_snapshot={
            "close_strength": 0.64,
            "sector_resonance": 0.33,
            "raw_catalyst_freshness": 0.27,
            "layer_c_alignment": 0.41,
            "long_trend_strength": 0.72,
            "event_freshness_strength": 0.55,
            "news_sentiment_strength": 0.44,
            "event_signal_strength": 0.58,
            "mean_reversion_strength": 0.12,
            "analyst_alignment": 0.35,
            "investor_alignment": 0.22,
            "analyst_penalty": 0.0,
            "investor_penalty": 0.0,
            "score_b_strength": 0.51,
            "score_c_strength": 0.42,
            "score_final_strength": 0.48,
            "momentum_strength": 0.78,
            "momentum_1m": 0.73,
            "momentum_3m": 0.67,
            "momentum_6m": 0.61,
            "volume_momentum": 0.59,
            "adx_strength": 0.71,
            "ema_strength": 0.69,
            "volatility_strength": 0.36,
            "volatility_metrics": {"volatility_regime": 0.22, "atr_ratio": 0.18},
            "trend_continuation": 0.88,
            "short_term_reversal": 0.12,
        },
        relief_snapshot={
            "breakout_freshness": 0.83,
            "trend_acceleration": 0.76,
            "volume_expansion_quality": 0.54,
            "catalyst_freshness": 0.31,
            "effective_near_miss_threshold": 0.55,
            "effective_select_threshold": 0.65,
            "selected_score_tolerance": 0.0,
            "market_state_threshold_adjustment": {},
            "selected_close_retention_adjustment": 0.0,
            "selected_close_retention_penalty": 0.0,
            "close_retention_score": 0.0,
            "breakout_close_gap": 0.0,
            "breakout_trap_guard": {},
            "layer_c_avoid_penalty": 0.0,
            "t_plus_2_continuation_candidate": {},
            "visibility_gap_continuation_relief": {},
            "merge_approved_continuation_relief": {},
            "historical_execution_relief": {},
            "historical_prior": {},
            "prepared_breakout_penalty_relief": {},
            "prepared_breakout_catalyst_relief": {},
            "prepared_breakout_volume_relief": {},
            "prepared_breakout_continuation_relief": {},
            "prepared_breakout_selected_catalyst_relief": {},
            "stale_trend_repair_penalty": 0.0,
            "overhead_supply_penalty": 0.0,
            "extension_without_room_penalty": 0.0,
            "event_catalyst_assessment": {},
            "positive_score_weights": {},
            "weighted_positive_contributions": {},
            "weighted_negative_contributions": {},
            "total_positive_contribution": 0.0,
            "total_negative_contribution": 0.0,
            "historical_continuation_prior_score": 0.0,
            "trend_continuation_strength_adjustment": 0.0,
            "score_target": 0.51,
            "profitability_relief": {
                "hard_cliff": False,
                "profitability_positive_count": 1,
                "profitability_confidence": 33.3333,
                "relief_enabled": False,
                "relief_gate_hits": {},
                "relief_eligible": False,
                "relief_applied": False,
                "soft_penalty": 0.0,
                "base_layer_c_avoid_penalty": 0.0,
            },
            "profitability_hard_cliff_boundary_relief": {},
            "upstream_shadow_catalyst_relief": {
                "enabled": False,
                "gate_hits": {},
                "eligible": False,
                "applied": False,
                "reason": "",
                "catalyst_freshness_floor": 0.0,
                "base_near_miss_threshold": 0.0,
                "near_miss_threshold_override": 0.0,
                "base_select_threshold": 0.0,
                "select_threshold_override": 0.0,
                "require_no_profitability_hard_cliff": False,
            },
            "catalyst_theme_penalty": {},
            "catalyst_theme_penalty_effective": 0.0,
            "watchlist_zero_catalyst_penalty": {},
            "watchlist_zero_catalyst_penalty_effective": 0.0,
            "watchlist_zero_catalyst_crowded_penalty": {},
            "watchlist_zero_catalyst_crowded_penalty_effective": 0.0,
            "watchlist_zero_catalyst_flat_trend_penalty": {},
            "watchlist_zero_catalyst_flat_trend_penalty_effective": 0.0,
            "watchlist_filter_diagnostics_flat_trend_penalty": {},
            "watchlist_filter_diagnostics_flat_trend_penalty_effective": 0.0,
            "watchlist_filter_diagnostics_selected_only_shrink_guard": {},
            "layer_c_watchlist_selected_only_shrink_guard": {
                "enabled": True,
                "eligible": True,
                "applied": True,
                "candidate_source": "layer_c_watchlist",
                "gate_hits": {"candidate_source": True},
                "select_threshold_lift": 0.04,
                "reason_code": "layer_c_watchlist_selected_only_shrink",
            },
            "short_trade_boundary_selected_only_shrink_guard": {
                "enabled": True,
                "eligible": True,
                "applied": True,
                "candidate_source": "short_trade_boundary",
                "gate_hits": {"candidate_source": True},
                "select_threshold_lift": 0.03,
                "reason_code": "short_trade_boundary_selected_only_shrink",
            },
        },
        labels_and_gates={
            "positive_tags": [],
            "negative_tags": [],
            "blockers": [],
            "gate_status": {},
        },
    )

    assert payload["trend_continuation"] == 0.88
    assert payload["short_term_reversal"] == 0.12
    assert payload["layer_c_watchlist_selected_only_shrink_guard"]["reason_code"] == "layer_c_watchlist_selected_only_shrink"
    assert payload["short_trade_boundary_selected_only_shrink_guard"]["select_threshold_lift"] == 0.03
