from __future__ import annotations

import os
from pathlib import Path

from src.execution.daily_pipeline_watchlist_helpers import WatchlistDiagnosticsConfig
from src.portfolio.position_calculator import STANDARD_EXECUTION_SCORE


def _get_env_float(name: str, default: float) -> float:
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    try:
        return float(raw_value)
    except ValueError:
        return default


def _get_env_int(name: str, default: int) -> int:
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    try:
        return int(raw_value)
    except ValueError:
        return default


def _get_env_csv_set(name: str, default: str) -> set[str]:
    raw_value = os.getenv(name, default)
    return {item.strip() for item in str(raw_value or "").split(",") if item.strip()}


def _get_env_csv_list(name: str, default: str) -> list[str]:
    raw_value = os.getenv(name, default)
    return [item.strip() for item in str(raw_value or "").split(",") if item.strip()]


FAST_AGENT_SCORE_THRESHOLD = _get_env_float("DAILY_PIPELINE_FAST_SCORE_THRESHOLD", 0.38)
FAST_AGENT_MAX_TICKERS = _get_env_int("DAILY_PIPELINE_FAST_POOL_MAX_SIZE", 12)
PRECISE_AGENT_MAX_TICKERS = _get_env_int("DAILY_PIPELINE_PRECISE_POOL_MAX_SIZE", 6)
WATCHLIST_SCORE_THRESHOLD = _get_env_float("DAILY_PIPELINE_WATCHLIST_SCORE_THRESHOLD", 0.20)
MERGE_APPROVED_SCORE_BOOST = _get_env_float("DAILY_PIPELINE_MERGE_APPROVED_SCORE_BOOST", 0.08)
MERGE_APPROVED_WATCHLIST_THRESHOLD_RELAXATION = _get_env_float("DAILY_PIPELINE_MERGE_APPROVED_WATCHLIST_THRESHOLD_RELAXATION", 0.05)
EXIT_REENTRY_CONFIRM_SCORE_MIN = _get_env_float("PIPELINE_EXIT_REENTRY_CONFIRM_SCORE_MIN", STANDARD_EXECUTION_SCORE)
EXIT_REENTRY_WEAK_CONFIRMATION_SCORE_MIN = _get_env_float("PIPELINE_EXIT_REENTRY_WEAK_CONFIRMATION_SCORE_MIN", 0.30)
CONTINUATION_EXECUTION_ENABLED = bool(_get_env_int("PIPELINE_CONTINUATION_EXECUTION_ENABLED", 1))
CONTINUATION_WATCHLIST_MIN_SCORE = _get_env_float("PIPELINE_CONTINUATION_WATCHLIST_MIN_SCORE", 0.21)
CONTINUATION_WATCHLIST_EDGE_EXECUTION_RATIO = _get_env_float("PIPELINE_CONTINUATION_WATCHLIST_EDGE_EXECUTION_RATIO", 0.3)
SHORT_TRADE_BOUNDARY_SCORE_BUFFER = _get_env_float("DAILY_PIPELINE_SHORT_TRADE_BOUNDARY_SCORE_BUFFER", 0.08)
SHORT_TRADE_BOUNDARY_MAX_TICKERS = _get_env_int("DAILY_PIPELINE_SHORT_TRADE_BOUNDARY_MAX_TICKERS", 6)
SHORT_TRADE_BOUNDARY_CANDIDATE_SCORE_MIN = _get_env_float("DAILY_PIPELINE_SHORT_TRADE_BOUNDARY_CANDIDATE_SCORE_MIN", 0.24)
SHORT_TRADE_BOUNDARY_BREAKOUT_MIN = _get_env_float("DAILY_PIPELINE_SHORT_TRADE_BOUNDARY_BREAKOUT_MIN", 0.18)
SHORT_TRADE_BOUNDARY_TREND_MIN = _get_env_float("DAILY_PIPELINE_SHORT_TRADE_BOUNDARY_TREND_MIN", 0.22)
SHORT_TRADE_BOUNDARY_VOLUME_MIN = _get_env_float("DAILY_PIPELINE_SHORT_TRADE_BOUNDARY_VOLUME_MIN", 0.15)
SHORT_TRADE_BOUNDARY_CATALYST_MIN = _get_env_float("DAILY_PIPELINE_SHORT_TRADE_BOUNDARY_CATALYST_MIN", 0.12)
UPSTREAM_SHADOW_OBSERVATION_MAX_TICKERS = _get_env_int("DAILY_PIPELINE_UPSTREAM_SHADOW_OBSERVATION_MAX_TICKERS", 3)
UPSTREAM_SHADOW_RELEASE_MAX_TICKERS = _get_env_int("DAILY_PIPELINE_UPSTREAM_SHADOW_RELEASE_MAX_TICKERS", 5)
UPSTREAM_SHADOW_RELEASE_CANDIDATE_SCORE_MIN = _get_env_float("DAILY_PIPELINE_UPSTREAM_SHADOW_RELEASE_CANDIDATE_SCORE_MIN", 0.30)
UPSTREAM_SHADOW_RELEASE_LANES = _get_env_csv_set(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_RELEASE_LANES",
    "layer_a_liquidity_corridor,post_gate_liquidity_competition",
)
UPSTREAM_SHADOW_RELEASE_LANE_SCORE_MINS = {
    "layer_a_liquidity_corridor": _get_env_float(
        "DAILY_PIPELINE_UPSTREAM_SHADOW_RELEASE_LIQUIDITY_CORRIDOR_SCORE_MIN",
        0.30,
    ),
    "post_gate_liquidity_competition": _get_env_float(
        "DAILY_PIPELINE_UPSTREAM_SHADOW_RELEASE_POST_GATE_REBUCKET_SCORE_MIN",
        UPSTREAM_SHADOW_RELEASE_CANDIDATE_SCORE_MIN,
    ),
}
UPSTREAM_SHADOW_RELEASE_LANE_MAX_TICKERS = {
    "layer_a_liquidity_corridor": _get_env_int(
        "DAILY_PIPELINE_UPSTREAM_SHADOW_RELEASE_LIQUIDITY_CORRIDOR_MAX_TICKERS",
        4,
    ),
    "post_gate_liquidity_competition": _get_env_int(
        "DAILY_PIPELINE_UPSTREAM_SHADOW_RELEASE_POST_GATE_REBUCKET_MAX_TICKERS",
        1,
    ),
}
UPSTREAM_SHADOW_RELEASE_SCORE_FLOOR_TREND_MIN = _get_env_float(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_RELEASE_SCORE_FLOOR_TREND_MIN",
    0.45,
)
UPSTREAM_SHADOW_RELEASE_SCORE_FLOOR_CLOSE_MIN = _get_env_float(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_RELEASE_SCORE_FLOOR_CLOSE_MIN",
    0.55,
)
UPSTREAM_SHADOW_RELEASE_PRIORITY_TICKERS_BY_LANE = {
    "layer_a_liquidity_corridor": _get_env_csv_list(
        "DAILY_PIPELINE_UPSTREAM_SHADOW_RELEASE_PRIORITY_LIQUIDITY_CORRIDOR_TICKERS",
        "",
    ),
    "post_gate_liquidity_competition": _get_env_csv_list(
        "DAILY_PIPELINE_UPSTREAM_SHADOW_RELEASE_PRIORITY_POST_GATE_REBUCKET_TICKERS",
        "",
    ),
}
UPSTREAM_SHADOW_CATALYST_RELIEF_CANDIDATE_SCORE_MIN = _get_env_float("DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_CANDIDATE_SCORE_MIN", 0.47)
UPSTREAM_SHADOW_CATALYST_RELIEF_BREAKOUT_MIN = _get_env_float("DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_BREAKOUT_MIN", 0.38)
UPSTREAM_SHADOW_CATALYST_RELIEF_TREND_MIN = _get_env_float("DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_TREND_MIN", 0.80)
UPSTREAM_SHADOW_CATALYST_RELIEF_CLOSE_MIN = _get_env_float("DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_CLOSE_MIN", 0.85)
UPSTREAM_SHADOW_CATALYST_RELIEF_CATALYST_FRESHNESS_FLOOR = _get_env_float("DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_CATALYST_FRESHNESS_FLOOR", 1.0)
UPSTREAM_SHADOW_CATALYST_RELIEF_NEAR_MISS_THRESHOLD = _get_env_float("DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_NEAR_MISS_THRESHOLD", 0.45)
UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_HARD_CLIFF_NEAR_MISS_THRESHOLD = _get_env_float(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_HARD_CLIFF_NEAR_MISS_THRESHOLD",
    0.42,
)
UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_SELECTED_THRESHOLD = _get_env_float(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_SELECTED_THRESHOLD",
    0.45,
)
UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_HARD_CLIFF_SELECTED_THRESHOLD = _get_env_float(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_HARD_CLIFF_SELECTED_THRESHOLD",
    0.43,
)
UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_HARD_CLIFF_TREND_MIN = _get_env_float(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_HARD_CLIFF_TREND_MIN",
    0.75,
)
UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_HARD_CLIFF_CLOSE_MIN = _get_env_float(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_HARD_CLIFF_CLOSE_MIN",
    0.80,
)
UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_HARD_CLIFF_HISTORY_NEXT_CLOSE_MIN = _get_env_float(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_HARD_CLIFF_HISTORY_NEXT_CLOSE_MIN",
    0.50,
)
UPSTREAM_SHADOW_CATALYST_RELIEF_HISTORY_REQUIRED_EXECUTION_QUALITY = _get_env_csv_set(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_HISTORY_REQUIRED_EXECUTION_QUALITY",
    "close_continuation",
)
UPSTREAM_SHADOW_CATALYST_RELIEF_HISTORY_MIN_EVALUABLE_COUNT = _get_env_int(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_HISTORY_MIN_EVALUABLE_COUNT",
    2,
)
UPSTREAM_SHADOW_CATALYST_RELIEF_HISTORY_NEXT_CLOSE_MIN = _get_env_float(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_HISTORY_NEXT_CLOSE_MIN",
    0.50,
)
UPSTREAM_SHADOW_CATALYST_RELIEF_HISTORY_NEXT_OPEN_TO_CLOSE_MIN = _get_env_float(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_HISTORY_NEXT_OPEN_TO_CLOSE_MIN",
    0.0,
)
UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_HARD_CLIFF_CANDIDATE_SCORE_MIN = _get_env_float(
    "DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_HARD_CLIFF_CANDIDATE_SCORE_MIN",
    0.44,
)
UPSTREAM_SHADOW_CATALYST_RELIEF_REQUIRE_NO_PROFITABILITY_HARD_CLIFF_DEFAULT = bool(
    _get_env_int("DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_REQUIRE_NO_PROFITABILITY_HARD_CLIFF", 1)
)
UPSTREAM_SHADOW_CATALYST_RELIEF_REQUIRE_NO_PROFITABILITY_HARD_CLIFF_BY_LANE = {
    "layer_a_liquidity_corridor": bool(
        _get_env_int("DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_LIQUIDITY_CORRIDOR_REQUIRE_NO_PROFITABILITY_HARD_CLIFF", 0)
    ),
    "post_gate_liquidity_competition": bool(
        _get_env_int(
            "DAILY_PIPELINE_UPSTREAM_SHADOW_CATALYST_RELIEF_POST_GATE_REBUCKET_REQUIRE_NO_PROFITABILITY_HARD_CLIFF",
            0,
        )
    ),
}
WATCHLIST_SHADOW_RELEASE_MAX_TICKERS = _get_env_int("DAILY_PIPELINE_WATCHLIST_SHADOW_RELEASE_MAX_TICKERS", 2)
WATCHLIST_SHADOW_RELEASE_SCORE_B_MIN = _get_env_float("DAILY_PIPELINE_WATCHLIST_SHADOW_RELEASE_SCORE_B_MIN", FAST_AGENT_SCORE_THRESHOLD)
WATCHLIST_SHADOW_RELEASE_SCORE_FINAL_MIN = _get_env_float("DAILY_PIPELINE_WATCHLIST_SHADOW_RELEASE_SCORE_FINAL_MIN", 0.18)
WATCHLIST_SHADOW_RELEASE_SCORE_C_MIN = _get_env_float("DAILY_PIPELINE_WATCHLIST_SHADOW_RELEASE_SCORE_C_MIN", -0.08)
WATCHLIST_SHADOW_RELEASE_CONFLICTS = _get_env_csv_set(
    "DAILY_PIPELINE_WATCHLIST_SHADOW_RELEASE_CONFLICTS",
    "b_positive_c_strong_bearish",
)
CATALYST_THEME_MAX_TICKERS = _get_env_int("DAILY_PIPELINE_CATALYST_THEME_MAX_TICKERS", 8)
CATALYST_THEME_SHADOW_MAX_TICKERS = _get_env_int("DAILY_PIPELINE_CATALYST_THEME_SHADOW_MAX_TICKERS", 8)
CATALYST_THEME_CANDIDATE_SCORE_MIN = _get_env_float("DAILY_PIPELINE_CATALYST_THEME_CANDIDATE_SCORE_MIN", 0.34)
CATALYST_THEME_BREAKOUT_MIN = _get_env_float("DAILY_PIPELINE_CATALYST_THEME_BREAKOUT_MIN", 0.10)
CATALYST_THEME_CLOSE_MIN = _get_env_float("DAILY_PIPELINE_CATALYST_THEME_CLOSE_MIN", 0.20)
CATALYST_THEME_SECTOR_MIN = _get_env_float("DAILY_PIPELINE_CATALYST_THEME_SECTOR_MIN", 0.25)
CATALYST_THEME_CATALYST_MIN = _get_env_float("DAILY_PIPELINE_CATALYST_THEME_CATALYST_MIN", 0.45)
CATALYST_THEME_CLOSE_MOMENTUM_RELIEF_BREAKOUT_MIN = 0.35
CATALYST_THEME_CLOSE_MOMENTUM_RELIEF_TREND_MIN = 0.72
CATALYST_THEME_CLOSE_MOMENTUM_RELIEF_CLOSE_MIN = 0.85
CATALYST_THEME_CLOSE_MOMENTUM_RELIEF_SECTOR_MIN = 0.10
CATALYST_THEME_SHORT_TRADE_CARRYOVER_CANDIDATE_SCORE_MIN = _get_env_float("DAILY_PIPELINE_CATALYST_THEME_SHORT_TRADE_CARRYOVER_CANDIDATE_SCORE_MIN", 0.45)
CATALYST_THEME_SHORT_TRADE_CARRYOVER_CATALYST_FRESHNESS_FLOOR = _get_env_float("DAILY_PIPELINE_CATALYST_THEME_SHORT_TRADE_CARRYOVER_CATALYST_FRESHNESS_FLOOR", 1.0)
CATALYST_THEME_SHORT_TRADE_CARRYOVER_NEAR_MISS_THRESHOLD = _get_env_float("DAILY_PIPELINE_CATALYST_THEME_SHORT_TRADE_CARRYOVER_NEAR_MISS_THRESHOLD", 0.44)
CATALYST_THEME_SHORT_TRADE_CARRYOVER_MIN_HISTORICAL_EVALUABLE_COUNT = _get_env_int(
    "DAILY_PIPELINE_CATALYST_THEME_SHORT_TRADE_CARRYOVER_MIN_HISTORICAL_EVALUABLE_COUNT",
    3,
)
CATALYST_THEME_SHORT_TRADE_CARRYOVER_REQUIRE_NO_PROFITABILITY_HARD_CLIFF = bool(
    _get_env_int("DAILY_PIPELINE_CATALYST_THEME_SHORT_TRADE_CARRYOVER_REQUIRE_NO_PROFITABILITY_HARD_CLIFF", 1)
)
BTST_REPORTS_ROOT = Path(os.getenv("DAILY_PIPELINE_BTST_REPORTS_ROOT", "data/reports")).expanduser()
MERGE_APPROVED_TICKERS = _get_env_csv_set("DAILY_PIPELINE_MERGE_APPROVED_TICKERS", "")
MERGE_APPROVED_MERGE_REVIEW_PATH = os.getenv("DAILY_PIPELINE_MERGE_APPROVED_MERGE_REVIEW_PATH", "")
MERGE_APPROVED_RANKING_PATH = os.getenv("DAILY_PIPELINE_MERGE_APPROVED_RANKING_PATH", "")
WATCHLIST_DIAGNOSTICS_CONFIG = WatchlistDiagnosticsConfig(
    watchlist_score_threshold=WATCHLIST_SCORE_THRESHOLD,
    shadow_release_max_tickers=WATCHLIST_SHADOW_RELEASE_MAX_TICKERS,
    shadow_release_score_b_min=WATCHLIST_SHADOW_RELEASE_SCORE_B_MIN,
    shadow_release_score_final_min=WATCHLIST_SHADOW_RELEASE_SCORE_FINAL_MIN,
    shadow_release_score_c_min=WATCHLIST_SHADOW_RELEASE_SCORE_C_MIN,
    shadow_release_conflicts=frozenset(WATCHLIST_SHADOW_RELEASE_CONFLICTS),
)
