from __future__ import annotations

import argparse
from pathlib import Path


SECTION_START = "<!-- LIVE_REPLAY_600519_P1:START -->"
SECTION_END = "<!-- LIVE_REPLAY_600519_P1:END -->"
DEFAULT_HEADING = "#### 9.11.7 Live Replay 实际结果"
DEFAULT_PLACEHOLDER = "- 待补：先运行 live replay 与 summary 脚本，再用 update 脚本自动回填本节。"


def _ensure_section(doc_text: str) -> str:
    if SECTION_START in doc_text and SECTION_END in doc_text:
        return doc_text

    block = "\n".join(
        [
            "",
            DEFAULT_HEADING,
            "",
            SECTION_START,
            DEFAULT_PLACEHOLDER,
            SECTION_END,
            "",
        ]
    )
    return doc_text.rstrip() + "\n" + block


def _replace_section(doc_text: str, summary_text: str) -> str:
    start_index = doc_text.index(SECTION_START) + len(SECTION_START)
    end_index = doc_text.index(SECTION_END)
    replacement = "\n\n" + summary_text.strip() + "\n\n"
    return doc_text[:start_index] + replacement + doc_text[end_index:]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Update the analysis doc with 600519 P1 live replay summary")
    parser.add_argument(
        "--doc",
        default="docs/zh-cn/analysis/layer-b-rule-variant-validation-20260312.md",
        help="Target analysis markdown file",
    )
    parser.add_argument(
        "--summary",
        default="data/reports/live_replay_600519_p1_summary.md",
        help="Summary markdown generated by summarize_live_replay_600519_p1.py",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print updated content to stdout without writing the doc")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root_dir = Path(__file__).resolve().parents[1]
    doc_path = (root_dir / args.doc).resolve()
    summary_path = (root_dir / args.summary).resolve()

    if not summary_path.exists():
        raise FileNotFoundError(f"Summary file not found: {summary_path}")

    doc_text = doc_path.read_text(encoding="utf-8")
    summary_text = summary_path.read_text(encoding="utf-8")
    updated_text = _replace_section(_ensure_section(doc_text), summary_text)

    if args.dry_run:
        print(updated_text)
        return 0

    doc_path.write_text(updated_text, encoding="utf-8")
    print(f"updated_doc: {doc_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())